Numpy Crash Course

In [1]:
import numpy as np
np.__version__

'1.26.4'

Creating Arrays

In [3]:
list = [0,1,2,3,4,5,6,7]
list

[0, 1, 2, 3, 4, 5, 6, 7]

In [4]:
type(list)

list

In [5]:
arr = np.array(list)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
type(arr)
# Both are Different

numpy.ndarray

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(3.0)

array([0., 1., 2.])

In [9]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [10]:
np.arange(-1050,1050,50)

array([-1050, -1000,  -950,  -900,  -850,  -800,  -750,  -700,  -650,
        -600,  -550,  -500,  -450,  -400,  -350,  -300,  -250,  -200,
        -150,  -100,   -50,     0,    50,   100,   150,   200,   250,
         300,   350,   400,   450,   500,   550,   600,   650,   700,
         750,   800,   850,   900,   950,  1000])

In [11]:
np.arange(50,-50)
# No data is given as the starting value is greater than the ending value

array([], dtype=int32)

In [12]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.ones((2,7),dtype=int)
# (rows,columns)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [15]:
n = (5,10)
print(np.ones(n,dtype=int))
# only zero and ones are printed

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [18]:
del list
# list is deleted

In [16]:
from numpy import *
arange(5)

array([0, 1, 2, 3, 4])

In [19]:
range(16)
list(range(16))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [20]:
from numpy import random

In [21]:
random.rand(5,5)

array([[0.77248938, 0.53090083, 0.00845729, 0.94647171, 0.13493554],
       [0.37676405, 0.19444112, 0.45889487, 0.98657455, 0.14550207],
       [0.20664579, 0.20280356, 0.5828792 , 0.3378081 , 0.18601516],
       [0.91799212, 0.50419302, 0.76534512, 0.80864497, 0.51500171],
       [0.29086334, 0.13928471, 0.8602301 , 0.40336124, 0.87658889]])

In [22]:
random.randint(1,3,5)

array([1, 2, 1, 2, 2])

In [23]:
random.randint(1)

0

In [24]:
random.randint(4,8)
# Gets a random number between 4 and 8

4

In [25]:
random.randint(100,190,5)

array([144, 113, 163, 141, 143])

In [26]:
random.randint(100,110,(10,10))
# 10 rows and 10 columns with random numbers between 100 and 110

array([[105, 104, 106, 103, 102, 103, 102, 103, 108, 100],
       [104, 100, 107, 103, 108, 104, 101, 101, 107, 104],
       [108, 109, 107, 103, 109, 102, 101, 104, 102, 104],
       [109, 101, 102, 106, 101, 106, 104, 104, 109, 108],
       [103, 103, 105, 106, 109, 100, 107, 108, 109, 109],
       [107, 102, 106, 104, 109, 101, 102, 108, 108, 108],
       [101, 102, 101, 102, 101, 108, 107, 107, 108, 109],
       [106, 103, 107, 106, 105, 100, 105, 104, 105, 101],
       [109, 101, 101, 106, 109, 105, 101, 101, 105, 108],
       [106, 107, 107, 107, 101, 102, 104, 106, 109, 107]])

In [27]:
b = random.randint(5,10,(4,3))
print(b)

[[9 9 7]
 [9 5 5]
 [7 5 8]
 [7 8 5]]


In [28]:
b[:]

array([[9, 9, 7],
       [9, 5, 5],
       [7, 5, 8],
       [7, 8, 5]])

In [29]:
b[:2]

array([[9, 9, 7],
       [9, 5, 5]])

In [30]:
b[0:-1]

array([[9, 9, 7],
       [9, 5, 5],
       [7, 5, 8]])

In [31]:
b[0,2]

7

In [ ]:
b[0,0:2]

array([9, 9])

Operations

In [33]:
a = random.randint(10,40,5)
print(a)

[33 13 38 38 37]


In [34]:
arr2 = random.randint(0,100,(10,10))
print(arr2)

[[35 86 99 34 76 67 19  6 97 86]
 [ 7 86  9 75 67 23 23 85 77  8]
 [69 98 52 22  5 45 60  4 34 32]
 [90 34 86  3 37 13 82 65 37 61]
 [58  6 15 58 92 44 30 71 60  0]
 [28 63 94 56 91 44 35 15 29  8]
 [30 76 21 45 96 37 32 99 32 62]
 [26 62 16 32 69 87 82 55 99 96]
 [26 83 32 64 35 46 13 17 77  9]
 [20 49 38 72 70 86  5 64 21 39]]


In [35]:
arr2[:]

array([[35, 86, 99, 34, 76, 67, 19,  6, 97, 86],
       [ 7, 86,  9, 75, 67, 23, 23, 85, 77,  8],
       [69, 98, 52, 22,  5, 45, 60,  4, 34, 32],
       [90, 34, 86,  3, 37, 13, 82, 65, 37, 61],
       [58,  6, 15, 58, 92, 44, 30, 71, 60,  0],
       [28, 63, 94, 56, 91, 44, 35, 15, 29,  8],
       [30, 76, 21, 45, 96, 37, 32, 99, 32, 62],
       [26, 62, 16, 32, 69, 87, 82, 55, 99, 96],
       [26, 83, 32, 64, 35, 46, 13, 17, 77,  9],
       [20, 49, 38, 72, 70, 86,  5, 64, 21, 39]])

In [36]:
arr2[0:3,0:3]
# Selected rows and columns

array([[35, 86, 99],
       [ 7, 86,  9],
       [69, 98, 52]])

In [38]:
arr2[4,6]

30

In [39]:
arr2[-1,-1]

39

In [40]:
arr2[-5]

array([28, 63, 94, 56, 91, 44, 35, 15, 29,  8])

In [41]:
arr2[::-1]
# Reverse the array

array([[20, 49, 38, 72, 70, 86,  5, 64, 21, 39],
       [26, 83, 32, 64, 35, 46, 13, 17, 77,  9],
       [26, 62, 16, 32, 69, 87, 82, 55, 99, 96],
       [30, 76, 21, 45, 96, 37, 32, 99, 32, 62],
       [28, 63, 94, 56, 91, 44, 35, 15, 29,  8],
       [58,  6, 15, 58, 92, 44, 30, 71, 60,  0],
       [90, 34, 86,  3, 37, 13, 82, 65, 37, 61],
       [69, 98, 52, 22,  5, 45, 60,  4, 34, 32],
       [ 7, 86,  9, 75, 67, 23, 23, 85, 77,  8],
       [35, 86, 99, 34, 76, 67, 19,  6, 97, 86]])

In [42]:
arr2[::-1,::-1]


array([[39, 21, 64,  5, 86, 70, 72, 38, 49, 20],
       [ 9, 77, 17, 13, 46, 35, 64, 32, 83, 26],
       [96, 99, 55, 82, 87, 69, 32, 16, 62, 26],
       [62, 32, 99, 32, 37, 96, 45, 21, 76, 30],
       [ 8, 29, 15, 35, 44, 91, 56, 94, 63, 28],
       [ 0, 60, 71, 30, 44, 92, 58, 15,  6, 58],
       [61, 37, 65, 82, 13, 37,  3, 86, 34, 90],
       [32, 34,  4, 60, 45,  5, 22, 52, 98, 69],
       [ 8, 77, 85, 23, 23, 67, 75,  9, 86,  7],
       [86, 97,  6, 19, 67, 76, 34, 99, 86, 35]])

In [43]:
arr2.shape

(10, 10)

In [44]:
arr2.max()

99

In [45]:
print(arr2.min())
print(arr2.max())
print(arr2.sum())
print(arr2.mean())
print(arr2.std())
print(arr2.var())

0
99
4911
49.11
29.37069798285359
862.6379


In [47]:
arr2.reshape(4,25)
# Can only be reshaped with same number of elements

array([[35, 86, 99, 34, 76, 67, 19,  6, 97, 86,  7, 86,  9, 75, 67, 23,
        23, 85, 77,  8, 69, 98, 52, 22,  5],
       [45, 60,  4, 34, 32, 90, 34, 86,  3, 37, 13, 82, 65, 37, 61, 58,
         6, 15, 58, 92, 44, 30, 71, 60,  0],
       [28, 63, 94, 56, 91, 44, 35, 15, 29,  8, 30, 76, 21, 45, 96, 37,
        32, 99, 32, 62, 26, 62, 16, 32, 69],
       [87, 82, 55, 99, 96, 26, 83, 32, 64, 35, 46, 13, 17, 77,  9, 20,
        49, 38, 72, 70, 86,  5, 64, 21, 39]])

Indexing

In [48]:
mat = np.arange(0,100).reshape(10,10)

print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [49]:
x = 5
y = 5
mat[x,y]

55

In [50]:
mat[:,y]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [51]:
mat[x:9]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [52]:
mat[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [53]:
mat[2:,4]

array([24, 34, 44, 54, 64, 74, 84, 94])

Masking

In [54]:
id(mat)

2363476961456

In [55]:
mat < 30

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [56]:
mat2 = random.randint(0,100,100).reshape(10,10)

In [57]:
mat2

array([[84, 17, 11, 44,  4, 43, 18, 40, 94, 67],
       [20, 21, 86, 28, 31, 50, 35, 16, 31, 52],
       [33, 62, 81, 62, 23, 82, 76, 38, 99,  7],
       [45, 23, 16,  8, 15, 68, 62, 31, 76,  0],
       [26, 53, 61, 12, 27, 95, 95, 31, 77, 14],
       [47, 24, 68, 68,  6, 76, 96, 43, 20, 69],
       [66, 82, 10, 80, 43, 77, 11, 73, 14, 17],
       [86,  9,  7, 19, 41, 91, 24, 58, 30, 69],
       [ 3, 54, 62, 87, 17, 77, 69, 96, 39, 75],
       [69, 47, 37, 27, 63, 19, 68, 66,  6, 48]])

In [58]:
mat2 > 50

array([[ True, False, False, False, False, False, False, False,  True,
         True],
       [False, False,  True, False, False, False, False, False, False,
         True],
       [False,  True,  True,  True, False,  True,  True, False,  True,
        False],
       [False, False, False, False, False,  True,  True, False,  True,
        False],
       [False,  True,  True, False, False,  True,  True, False,  True,
        False],
       [False, False,  True,  True, False,  True,  True, False, False,
         True],
       [ True,  True, False,  True, False,  True, False,  True, False,
        False],
       [ True, False, False, False, False,  True, False,  True, False,
         True],
       [False,  True,  True,  True, False,  True,  True,  True, False,
         True],
       [ True, False, False, False,  True, False,  True,  True, False,
        False]])

In [59]:
mat2[mat2==6]

array([6, 6])

In [60]:
mat2[mat2==68]

array([68, 68, 68, 68])

In [62]:
c = mat2[mat2<20]
c

array([17, 11,  4, 18, 16,  7, 16,  8, 15,  0, 12, 14,  6, 10, 11, 14, 17,
        9,  7, 19,  3, 17, 19,  6])